
CREATE TABLE USUARIO (
    USUARIO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ADMINISTRADOR_FAMILIAR_ID NUMERIC(10,0),
    NOMBRE VARCHAR2(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(40),
    USERNAME VARCHAR2(40) NOT NULL,
    PASSWORD VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    RFC VARCHAR2(13) NOT NULL,
    CONSTRAINT usuario_pk PRIMARY KEY (USUARIO_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT usuario_admin_fk FOREIGN KEY (ADMINISTRADOR_TITULAR_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT usuario_username_uk UNIQUE (USERNAME) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT usuario_email_uk UNIQUE (EMAIL) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT usuario_rfc_uk UNIQUE (RFC) USING INDEX TABLESPACE usuarios_c1_idx_ts
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX usuario_admin_idx ON USUARIO(ADMINISTRADOR_TITULAR_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE PLAN (
    PLAN_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    CLAVE VARCHAR2(40) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    COSTO NUMERIC(10,2) NOT NULL,
    DESCRIPCION VARCHAR2(400) NOT NULL,
    CONSTRAINT plan_pk PRIMARY KEY (PLAN_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT plan_clave_uk UNIQUE (CLAVE) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT plan_costo_chk CHECK (COSTO >= 0)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE TABLE TARJETA_CLIENTE (
    TARJETA_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MES VARCHAR2(2) NOT NULL,
    ANIO VARCHAR2(4) NOT NULL,
    CVV VARCHAR2(4) NOT NULL,
    NUMERO VARCHAR2(16) NOT NULL,
    TIPO VARCHAR2(40) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT tarjeta_cuenta_pk PRIMARY KEY (TARJETA_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT tarjeta_cuenta_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT tarjeta_cuenta_numero_uk UNIQUE (NUMERO) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT tarjeta_cuenta_mes_chk CHECK (TO_NUMBER(MES) BETWEEN 1 AND 12)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX tarjeta_cuenta_usuario_idx ON TARJETA_CUENTA(USUARIO_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE DISPOSITIVO (
    DISPOSITIVO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TIPO VARCHAR2(40) NOT NULL,
    IP VARCHAR2(15) NOT NULL,
    SO VARCHAR2(40) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    MARCA VARCHAR2(40) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT dispositivo_pk PRIMARY KEY (DISPOSITIVO_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT dispositivo_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX dispositivo_usuario_idx ON DISPOSITIVO(USUARIO_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE PLAN_HISTORICO (
    PLAN_HISTORICO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    COSTO NUMERIC(10,2) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PLAN_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT plan_historico_pk PRIMARY KEY (PLAN_HISTORICO_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT plan_historico_plan_fk FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID),
    CONSTRAINT plan_historico_fechas_chk CHECK (FECHA_FIN >= FECHA_INICIO)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX plan_historico_plan_idx ON PLAN_HISTORICO(PLAN_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE CARGO (
    CARGO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA_CARGO DATE NOT NULL,
    IMPORTE NUMERIC(10,2) NOT NULL,
    TARJETA_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT cargo_pk PRIMARY KEY (CARGO_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT cargo_tarjeta_fk FOREIGN KEY (TARJETA_ID) REFERENCES TARJETA_CUENTA(TARJETA_ID),
    CONSTRAINT cargo_importe_chk CHECK (IMPORTE >= 0)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX cargo_tarjeta_idx ON CARGO(TARJETA_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE VIP_OPERACION (
    VIP_OPERACION_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FOLIO VARCHAR2(8) NOT NULL,
    TIPO_OPERACION VARCHAR2(20) NOT NULL,
    FECHA_COMPRA DATE,
    PERIODO_RENTA NUMERIC(10,0),
    CARGO_ID NUMERIC(10,0) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT vip_operacion_pk PRIMARY KEY (VIP_OPERACION_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT vip_operacion_folio_uk UNIQUE (FOLIO) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT vip_operacion_cargo_fk FOREIGN KEY (CARGO_ID) REFERENCES CARGO(CARGO_ID),
    CONSTRAINT vip_operacion_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT vip_operacion_folio_chk CHECK (LENGTH(FOLIO) = 8)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX vip_operacion_cargo_idx ON VIP_OPERACION(CARGO_ID) TABLESPACE usuarios_c1_idx_ts;
CREATE INDEX vip_operacion_usuario_idx ON VIP_OPERACION(USUARIO_ID) TABLESPACE usuarios_c1_idx_ts;

CREATE TABLE USUARIO_SUSCRIPCION (
    USUARIO_SUSCRIPCION_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    PLAN_ID NUMERIC(10,0) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    STATUS VARCHAR2(40) NOT NULL,
    CONSTRAINT usuario_suscripcion_pk PRIMARY KEY (USUARIO_SUSCRIPCION_ID) USING INDEX TABLESPACE usuarios_c1_idx_ts,
    CONSTRAINT us_suscripcion_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT us_suscripcion_plan_fk FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID),
    CONSTRAINT us_suscripcion_fechas_chk CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
) PCTFREE 10 TABLESPACE usuarios_c1_data_ts;

CREATE INDEX us_suscripcion_usuario_idx ON USUARIO_SUSCRIPCION(USUARIO_ID) TABLESPACE usuarios_c1_idx_ts;
CREATE INDEX us_suscripcion_plan_idx ON USUARIO_SUSCRIPCION(PLAN_ID) TABLESPACE usuarios_c1_idx_ts;

