Prompt Conectando a la PDB de media y configurando el esquema
CONNECT sys/"Hola1234*" as sysdba
ALTER SESSION SET CONTAINER = media_pdb;
ALTER SESSION SET CURRENT_SCHEMA = david_media;

CREATE TABLE USUARIO (
    USUARIO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ADMINISTRADOR_FAMILIAR_ID NUMERIC(10,0),
    USERNAME VARCHAR2(40) NOT NULL,
    PASSWORD VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CONSTRAINT usuario_foraneo_pk PRIMARY KEY (USUARIO_ID) USING INDEX TABLESPACE media_c1_idx_ts
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE CONTENIDO_GENERO (
    GENERO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(400),
    CONSTRAINT genero_pk PRIMARY KEY (GENERO_ID) USING INDEX TABLESPACE media_c1_idx_ts
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE CONTENIDO_STATUS (
    CONTENIDO_STATUS_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    STATUS VARCHAR2(40) NOT NULL,
    DESCRIPCION VARCHAR2(400),
    CONSTRAINT contenido_status_pk PRIMARY KEY (CONTENIDO_STATUS_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT contenido_status_chk CHECK (STATUS IN ('por estrenarse', 'en línea', 'suspendido', 'retirado'))
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE SERIE (
    SERIE_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL,
    FECHA_LANZAMIENTO DATE NOT NULL,
    CONSTRAINT serie_pk PRIMARY KEY (SERIE_ID) USING INDEX TABLESPACE media_c1_idx_ts
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE ALBUM (
    ALBUM_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL,
    FECHA_LANZAMIENTO DATE NOT NULL,
    IMAGEN BLOB NOT NULL,
    CONSTRAINT album_pk PRIMARY KEY (ALBUM_ID) USING INDEX TABLESPACE media_c1_idx_ts
) PCTFREE 10 TABLESPACE media_c1_data_ts
LOB (IMAGEN) STORE AS SECUREFILE album_imagen_lob (
    TABLESPACE media_c2_lob_ts
);

CREATE TABLE AUTOR (
    AUTOR_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(40),
    EMAIL VARCHAR2(100) NOT NULL,
    NOMBRE_ARTISTICO VARCHAR2(100) NOT NULL,
    CONSTRAINT autor_pk PRIMARY KEY (AUTOR_ID) USING INDEX TABLESPACE media_c1_idx_ts
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE CONTENIDO_MULTIMEDIA (
    CONTENIDO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    CLAVE VARCHAR2(16) NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL,
    TOTAL_REPRODUCCIONES NUMERIC(10,0) DEFAULT 0 NOT NULL,
    DURACION NUMERIC(10,0) NOT NULL,
    GENERO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT contenido_multimedia_pk PRIMARY KEY (CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT contenido_multimedia_clave_uk UNIQUE (CLAVE) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT contenido_multimedia_genero_fk FOREIGN KEY (GENERO_ID) REFERENCES CONTENIDO_GENERO(GENERO_ID),
    CONSTRAINT contenido_multimedia_clave_chk CHECK (LENGTH(CLAVE) = 16)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX cont_mult_genero_idx ON CONTENIDO_MULTIMEDIA(GENERO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE AUDIO (
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    LETRA CLOB,
    FORMATO VARCHAR2(10) NOT NULL,
    KBPS NUMERIC(10,0) NOT NULL,
    ALBUM_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT audio_pk PRIMARY KEY (CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT audio_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID),
    CONSTRAINT audio_album_fk FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ALBUM_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts
LOB (LETRA) STORE AS SECUREFILE audio_letra_lob (
    TABLESPACE media_c2_lob_ts
);

CREATE INDEX audio_album_idx ON AUDIO(ALBUM_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE VIDEO (
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    TIPO_VIDEO VARCHAR2(40) NOT NULL,
    CLASIFICACION VARCHAR2(1) NOT NULL,
    TIPO_CODIFICACION VARCHAR2(20) NOT NULL,
    TIPO_TRANSPORTE VARCHAR2(20) NOT NULL,
    PROTOCOLO_TRANSMISION VARCHAR2(20) NOT NULL,
    SERIE_ID NUMERIC(10,0),
    CONSTRAINT video_pk PRIMARY KEY (CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT video_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID),
    CONSTRAINT video_serie_fk FOREIGN KEY (SERIE_ID) REFERENCES SERIE(SERIE_ID),
    CONSTRAINT video_clasificacion_chk CHECK (CLASIFICACION IN ('A', 'B', 'C', 'D'))
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX video_serie_idx ON VIDEO(SERIE_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE VIDEO_FRAGMENTO (
    FRAGMENTO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    SECUENCIA NUMERIC(10,0) NOT NULL,
    CONTENIDO BLOB NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT video_fragmento_pk PRIMARY KEY (FRAGMENTO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT video_fragmento_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES VIDEO(CONTENIDO_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts
LOB (CONTENIDO) STORE AS SECUREFILE video_contenido_lob (
    TABLESPACE media_c2_lob_ts
);

CREATE INDEX video_fragmento_cont_idx ON VIDEO_FRAGMENTO(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE VIP_CONTENIDO (
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    COSTO_RENTA NUMERIC(10,2) NOT NULL,
    COSTO_VENTA NUMERIC(10,2) NOT NULL,
    VIGENCIA_INICIO DATE NOT NULL,
    VIGENCIA_FIN DATE NOT NULL,
    CONSTRAINT vip_contenido_pk PRIMARY KEY (CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT vip_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES VIDEO(CONTENIDO_ID),
    CONSTRAINT vip_contenido_fechas_chk CHECK (VIGENCIA_FIN >= VIGENCIA_INICIO)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE TABLE CONTENIDO_STATUS_HISTORICO (
    HISTORICO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA DATE NOT NULL,
    CONTENIDO_STATUS_ID NUMERIC(10,0) NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT status_historico_pk PRIMARY KEY (HISTORICO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT status_historico_status_fk FOREIGN KEY (CONTENIDO_STATUS_ID) REFERENCES CONTENIDO_STATUS(CONTENIDO_STATUS_ID),
    CONSTRAINT status_historico_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX status_hist_status_idx ON CONTENIDO_STATUS_HISTORICO(CONTENIDO_STATUS_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX status_hist_cont_idx ON CONTENIDO_STATUS_HISTORICO(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE AUTOR_CONTENIDO (
    AUTOR_CONTENIDO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    PARTICIPACION NUMERIC(5,2) NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    AUTOR_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT autor_contenido_pk PRIMARY KEY (AUTOR_CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT autor_contenido_cont_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID),
    CONSTRAINT autor_contenido_autor_fk FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR(AUTOR_ID),
    CONSTRAINT autor_contenido_part_chk CHECK (PARTICIPACION BETWEEN 0 AND 100)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX autor_cont_cont_idx ON AUTOR_CONTENIDO(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX autor_cont_autor_idx ON AUTOR_CONTENIDO(AUTOR_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE REPRODUCCION (
    REPRODUCCION_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA DATE NOT NULL,
    SEGUNDO_INICIAL NUMERIC(10,0) NOT NULL,
    SEGUNDO_FINAL NUMERIC(10,0) NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT reproduccion_pk PRIMARY KEY (REPRODUCCION_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT reproduccion_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID),
    CONSTRAINT reproduccion_usuario_fk KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT reproduccion_segundos_chk CHECK (SEGUNDO_FINAL >= SEGUNDO_INICIAL)
) PCTFREE 10 
PARTITION BY RANGE (FECHA) (
    PARTITION rep_q1_2026 VALUES LESS THAN (TO_DATE('01-04-2026', 'DD-MM-YYYY')) TABLESPACE media_c1_data_ts,
    PARTITION rep_q2_2026 VALUES LESS THAN (TO_DATE('01-07-2026', 'DD-MM-YYYY')) TABLESPACE media_c1_data_ts,
    PARTITION rep_q3_2026 VALUES LESS THAN (TO_DATE('01-10-2026', 'DD-MM-YYYY')) TABLESPACE media_c1_data_ts,
    PARTITION rep_q4_2026 VALUES LESS THAN (MAXVALUE) TABLESPACE media_c1_data_ts
);

CREATE INDEX reprod_cont_idx ON REPRODUCCION(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX reprod_usuario_idx ON REPRODUCCION(USUARIO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE COMENTARIO (
    COMENTARIO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHA DATE NOT NULL,
    TEXTO_COMENTARIO VARCHAR2(1000) NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL, 
    COMENTARIO_PADRE_ID NUMERIC(10,0), 
    CONSTRAINT comentario_pk PRIMARY KEY (COMENTARIO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT comentario_contenido_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID),
    CONSTRAINT comentario_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT comentario_respuesta_fk FOREIGN KEY (COMENTARIO_PADRE_ID) REFERENCES COMENTARIO(COMENTARIO_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX comentario_cont_idx ON COMENTARIO(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX comentario_usuario_idx ON COMENTARIO(USUARIO_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX comentario_resp_idx ON COMENTARIO(COMENTARIO_PADRE_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE PLAYLIST (
    PLAYLIST_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    ESTRELLAS NUMERIC(1,0),
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT playlist_pk PRIMARY KEY (PLAYLIST_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT playlist_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT playlist_estrellas_chk CHECK (ESTRELLAS BETWEEN 1 AND 5)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX playlist_usuario_idx ON PLAYLIST(USUARIO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE PLAYLIST_CONTENIDO (
    PLAYLIST_CONTENIDO_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    PLAYLIST_ID NUMERIC(10,0) NOT NULL,
    CONTENIDO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT playlist_contenido_pk PRIMARY KEY (PLAYLIST_CONTENIDO_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT playlist_contenido_play_fk FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(PLAYLIST_ID),
    CONSTRAINT playlist_contenido_cont_fk FOREIGN KEY (CONTENIDO_ID) REFERENCES CONTENIDO_MULTIMEDIA(CONTENIDO_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX play_cont_play_idx ON PLAYLIST_CONTENIDO(PLAYLIST_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX play_cont_cont_idx ON PLAYLIST_CONTENIDO(CONTENIDO_ID) TABLESPACE media_c1_idx_ts;

CREATE TABLE PLAYLIST_COMPARTIDA (
    PLAYLIST_COMPARTIDA_ID NUMERIC(10,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    PLAYLIST_ID NUMERIC(10,0) NOT NULL,
    USUARIO_ID NUMERIC(10,0) NOT NULL,
    CONSTRAINT playlist_compartida_pk PRIMARY KEY (PLAYLIST_COMPARTIDA_ID) USING INDEX TABLESPACE media_c1_idx_ts,
    CONSTRAINT playlist_compartida_play_fk FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(PLAYLIST_ID),
    CONSTRAINT playlist_compartida_usuario_fk FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
) PCTFREE 10 TABLESPACE media_c1_data_ts;

CREATE INDEX play_comp_play_idx ON PLAYLIST_COMPARTIDA(PLAYLIST_ID) TABLESPACE media_c1_idx_ts;
CREATE INDEX play_comp_usuario_idx ON PLAYLIST_COMPARTIDA(USUARIO_ID) TABLESPACE media_c1_idx_ts;

Prompt Listo!
exit
